CREATE TABLE `gifts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`token` varchar(128) NOT NULL,
	`senderUserId` int NOT NULL,
	`recipientEmail` varchar(320) NOT NULL,
	`recipientName` varchar(255),
	`message` text,
	`productKey` varchar(32) NOT NULL,
	`stripeSessionId` varchar(255) NOT NULL,
	`amountCents` int NOT NULL,
	`currency` varchar(8) NOT NULL DEFAULT 'usd',
	`status` enum('pending','redeemed') NOT NULL DEFAULT 'pending',
	`redeemedByUserId` int,
	`redeemedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `gifts_id` PRIMARY KEY(`id`),
	CONSTRAINT `gifts_token_unique` UNIQUE(`token`),
	CONSTRAINT `gifts_stripeSessionId_unique` UNIQUE(`stripeSessionId`)
);
